### ISSUE TITLE
[BUG] Measurements missing "state_class: measurement"

### ISSUE THREAD

**Issue by madejackson** [modbus2mqtt/server#34]
OT: Sorry for posting so much issues. Don't get me wrong, I like the work you have done and I just want to give feedback :)

Measurements in Home Assistant should be `state_class: measurement` to support [long-term-statistics](https://developers.home-assistant.io/docs/core/entity/sensor/?_highlight=state_class#long-term-statistics).

See a sensor I included twice, first directly via modbus and then via modbus2mqtt. You can see the better display on the first image as it uses min, max and median values to display.

![image](https://github.com/user-attachments/assets/27e898db-3344-4be3-8446-12e3b4666e10)
![image](https://github.com/user-attachments/assets/3294a828-084f-492e-a087-f40ddcea85e7)

Config of direct modbus integration:
```
modbus:
  - name: mbusd-ttyACM2
    type: tcp
    host: mbusd-ttyACM2
    port: 502
    sensors:
      - name: "WRF06 Temp"
        unique_id: "781923_temp"
        unit_of_measurement: °C
        slave: 1
        address: 0
        scale: 0.1
        precision: 1
        state_class: measurement
```
